---
- name: Install docker dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: true

  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common


- name: Setup Docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  environment: "{{ proxy_env }}"

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  environment: "{{ proxy_env }}"


- name: Install Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes

  loop:
    - docker-ce
    - docker-ce-cli
    - containered.io
  environment: "{{ proxy_env }}"


- name: Start and enable Docker service
  service:
    name: docker
    state: startet
    enabled: yes